### PR TITLE
#161048150 Create login page 

### PR DESCRIPTION
**Pull request by JoshuaKodhe**
#### What does this PR do?
This will create a login page

#### Description of Task to be completed?
Have a page where users can enter their 
username/email and passwords and be able to
log in by clicking on the login button
#### How should this be manually tested?
Clone the repository, change into the project folder
   use : cd /path/to/cloned/project

#### Any background context you want to provide?
This is to allow a user to access services offered

#### What are the relevant pivotal tracker stories?
 #161048150 

#### Screenshots 

screenshot from 2018-10-09 01-38-07

### CODE REVIEW

**Comment by wandesky** [comment]
Nice login. Very elegant.

**Comment by JoshuaKodhe** [comment]
@wandesky thank you

**Comment by Allan690** [comment]
Nice one

**Comment by waracci** [comment]
Simplistic UI :+1: 
But your navbar could use some more links.

**Comment by JoshuaKodhe** [comment]
Thank you for the feedback
I am going to work on it.

On 09/10/2018, Morris Warachi <notifications@github.com> wrote:
> Simplistic UI :+1:
> But your navbar could use some more links.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/JoshuaKodhe/Store-Manager/pull/2#issuecomment-428072694


-- 
Kodhe Joshua

**Comment by Paulvitalis200** [comment]
Nice!!

**Pull request merged**
